name: PySide6 CI
on:
  push:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Run every day at 00:00 UTC.

jobs:
  build-package:
    name: "Build the PySide6 package for Fedora ${{matrix.version}}"
    runs-on: ubuntu-latest
    container: fedora:${{ matrix.version }}
    strategy:
      matrix:
        include:
          - version: "38"
          - version: "39"
    env:
      rpm_name: python3-pyside6-6.6.3.1-1.fc${{matrix.version}}.x86_64.rpm
      srpm_name: python3-pyside6-6.6.3.1-1.fc${{matrix.version}}.src.rpm
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        run: dnf install -y rpm-build python3-devel
      - name: Build the PySide6 package
        run: ./build.sh
      - name: Upload binary RPM
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.rpm_name }}
          path: ".rpmbuild/RPMS/x86_64/${{ env.rpm_name }}"
          if-no-files-found: error
          compression-level: 0
      - name: Upload source RPM
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.srpm_name }}
          path: ".rpmbuild/SRPMS/${{ env.srpm_name }}"
          if-no-files-found: error
          compression-level: 0

  check-updates:
    name: "Ensure our package does not lag behind the PyPI one"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install -y python3-requests
      - name: Check if there is a PySide6 update
        run: ./check_updates.py
