name: PySide6 CI
on:
  push:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Run every day at 00:00 UTC.

jobs:
  build-package:
    name: "Build the PySide6 package for Fedora ${{matrix.version}}"
    runs-on: ubuntu-latest
    container: fedora:${{ matrix.version }}
    strategy:
      matrix:
        include:
          - version: "39"
          - version: "40"
          # NOTE: Fedora 41 ships with Python 3.13, which is incompatible with
          # PySide6 6.7.1. On the other hand, the candidate PySide6 package by
          # Fedora offers a fix [1] for this issue, and at some point should be
          # offered officially.
          #
          # So, given that we have alternatives, we remove Fedora 41 from our CI
          # tests, and may re-introduce it if an upstream PySide6 version adds
          # support for Python 3.13.
          #
          # [1]: https://src.fedoraproject.org/fork/luk1337/rpms/python-pyside6/c/f9852fa14d755f16c06c9f0247325da62cffdfd0
          #
          #- version: "41"
    env:
      rpm_name: python3-pyside6-6.7.1-1.fc${{matrix.version}}.x86_64.rpm
      srpm_name: python3-pyside6-6.7.1-1.fc${{matrix.version}}.src.rpm
    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: dnf install -y rpm-build python3-devel
      - name: Build the PySide6 package
        run: ./build.sh
      - name: Upload binary RPM
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.rpm_name }}
          path: ".rpmbuild/RPMS/x86_64/${{ env.rpm_name }}"
          if-no-files-found: error
          compression-level: 0
      - name: Upload source RPM
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.srpm_name }}
          path: ".rpmbuild/SRPMS/${{ env.srpm_name }}"
          if-no-files-found: error
          compression-level: 0
